// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.DTO
{
    public partial class AppliedStudentList
    {
        public Guid UserProfileId { get; set; }
        public long RegistrationNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public long MobileNumber { get; set; }
       
        public DateTime Dob { get; set; }
        public string CourseName { get; set; }



    }
}