// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.DTO
{
    public partial class JobMasterDTO
    {
        public Guid JobId { get; set; }
        public Guid? UserProfileId { get; set; }
        public string JobDesignation { get; set; }
        public string CompanyName { get; set; }
        public Guid? CountryId { get; set; }
        public Guid? StateId { get; set; }
        public Guid? DistrictId { get; set; }
        public Guid? CityId { get; set; }
        public long MinExperience { get; set; }
        public long MaxExperience { get; set; }
        public string Description { get; set; }
        public DateTime? LastDate { get; set; }
        public string Ctc { get; set; }
        public DateTime? ExpectedJoiningDate { get; set; }
        public long? NoOfOpening { get; set; }
        public string Category { get; set; }
        public string Industry { get; set; }
        public string WorkShift { get; set; }
        public string JobLevel { get; set; }
        public string IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }

    }
}