// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.DTO
{
    public partial class QuestionnaireResultDTO
    {
        public Guid QuestionnaireResultId { get; set; }
        public Guid? CandidateResultId { get; set; }
        public Guid? QuestionnaireId { get; set; }
        public bool? AnswerProvided { get; set; }
        public int? QuestionOrder { get; set; }
        public int? OptionSelected { get; set; }

        
    }
}