// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.DTO
{
    public partial class ResponseResult
    {
        public bool Error { get; set; }
        public string Message { get; set; }
        public string Id { get; set; }
        public object Model { get; set; }
        public int MaxCount{ get; set; }
        public object CheckAnswerProvided { get; set; }
    }
}