// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class Address
    {
        [Key]
        public Guid AddressId { get; set; }
        public Guid? UserProfileId { get; set; }
        [StringLength(20)]
        public string AddressType { get; set; }
        [StringLength(150)]
        public string Line1 { get; set; }
        [StringLength(150)]
        public string Line2 { get; set; }
        [StringLength(150)]
        public string Line3 { get; set; }
        public Guid? CountryId { get; set; }
        public Guid? StateId { get; set; }
        public Guid? DistrictId { get; set; }
        public Guid? CityId { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CityId))]
        [InverseProperty(nameof(CityMaster.Address))]
        public virtual CityMaster City { get; set; }
        [ForeignKey(nameof(CountryId))]
        [InverseProperty(nameof(CountryMaster.Address))]
        public virtual CountryMaster Country { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.AddressCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(DistrictId))]
        [InverseProperty(nameof(DistrictMaster.Address))]
        public virtual DistrictMaster District { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.AddressModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [ForeignKey(nameof(StateId))]
        [InverseProperty(nameof(StateMaster.Address))]
        public virtual StateMaster State { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("Address")]
        public virtual UserProfile UserProfile { get; set; }
    }
}