// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class Admission
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? UserProfileId { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        [StringLength(100)]
        public string MiddleName { get; set; }
        [StringLength(100)]
        public string LastName { get; set; }
        public long? MobileNumber { get; set; }
        [StringLength(100)]
        public string EmailAddress { get; set; }
        public long? FeeAmount { get; set; }
        [StringLength(100)]
        public string FeeMode { get; set; }
        [StringLength(250)]
        public string ReceiptNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PaidDate { get; set; }
        [StringLength(250)]
        public string PaidBankName { get; set; }
        [Column("PaidBankIFSCcode")]
        [StringLength(100)]
        public string PaidBankIfsccode { get; set; }
        public Guid? CourseId { get; set; }
        public string Comments { get; set; }
        public Guid? CollegeProfileId { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(CollegeProfileId))]
        [InverseProperty("Admission")]
        public virtual CollegeProfile CollegeProfile { get; set; }
        [ForeignKey(nameof(CourseId))]
        [InverseProperty(nameof(CourseMaster.Admission))]
        public virtual CourseMaster Course { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.AdmissionCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.AdmissionUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("Admission")]
        public virtual UserProfile UserProfile { get; set; }
    }
}