// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class AppliedJobs
    {
        public AppliedJobs()
        {
            ShortlistedCandidates = new HashSet<ShortlistedCandidates>();
        }

        [Key]
        public Guid AppliedJobId { get; set; }
        public Guid? UserProfileId { get; set; }
        public Guid? JobId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AppliedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StatusUpdatedDate { get; set; }
        [StringLength(100)]
        public string Status { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.AppliedJobsCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(JobId))]
        [InverseProperty(nameof(JobMaster.AppliedJobs))]
        public virtual JobMaster Job { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.AppliedJobsModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("AppliedJobs")]
        public virtual UserProfile UserProfile { get; set; }
        [InverseProperty("AppliedJob")]
        public virtual ICollection<ShortlistedCandidates> ShortlistedCandidates { get; set; }
    }
}