// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class ApprovalJobs
    {
        [Key]
        public Guid ApprovalJobId { get; set; }
        public Guid? UserProfileId { get; set; }
        public Guid? JobId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ApprovalDate { get; set; }
        [StringLength(100)]
        public string Status { get; set; }
        [StringLength(10)]
        public string IsActive { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime ModifiedDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.ApprovalJobsCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(JobId))]
        [InverseProperty(nameof(JobMaster.ApprovalJobs))]
        public virtual JobMaster Job { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.ApprovalJobsModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("ApprovalJobs")]
        public virtual UserProfile UserProfile { get; set; }
    }
}