// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class CandidateCollegeMapping
    {
        [Key]
        public Guid CandidateCollegeId { get; set; }
        public Guid? UserProfileId { get; set; }
        public Guid? CollegeProfileId { get; set; }
        public bool? IsActive { get; set; }
        [Column("PPOGenerated")]
        public bool? Ppogenerated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }

        [ForeignKey(nameof(CollegeProfileId))]
        [InverseProperty("CandidateCollegeMapping")]
        public virtual CollegeProfile CollegeProfile { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CandidateCollegeMappingCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.CandidateCollegeMappingUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("CandidateCollegeMapping")]
        public virtual UserProfile UserProfile { get; set; }
    }
}