// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class CandidateResult
    {
        public CandidateResult()
        {
            QuestionnaireResult = new HashSet<QuestionnaireResult>();
        }

        [Key]
        public Guid CandidateResultId { get; set; }
        [Column("UserCoursesID")]
        public Guid? UserCoursesId { get; set; }
        public int? TestDuration { get; set; }
        public bool? IsCompleted { get; set; }
        public bool? IsCleared { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TestStarted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RemainingTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TestEnd { get; set; }
        public Guid? PaymentHistoryId { get; set; }
        public int? TestAttempt { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Score { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CandidateResult))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(PaymentHistoryId))]
        [InverseProperty("CandidateResult")]
        public virtual PaymentHistory PaymentHistory { get; set; }
        [ForeignKey(nameof(UserCoursesId))]
        [InverseProperty("CandidateResult")]
        public virtual UserCourses UserCourses { get; set; }
        [InverseProperty("CandidateResult")]
        public virtual ICollection<QuestionnaireResult> QuestionnaireResult { get; set; }
    }
}