// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class CandidateTrainingStatus
    {
        [Key]
        public Guid CandidateTrainingStatusId { get; set; }
        [Column("UserCoursesID")]
        public Guid? UserCoursesId { get; set; }
        public Guid? TrainingContentId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DownloadedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompletedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CandidateTrainingStatus))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(TrainingContentId))]
        [InverseProperty(nameof(TrainingContentsMaster.CandidateTrainingStatus))]
        public virtual TrainingContentsMaster TrainingContent { get; set; }
        [ForeignKey(nameof(UserCoursesId))]
        [InverseProperty("CandidateTrainingStatus")]
        public virtual UserCourses UserCourses { get; set; }
    }
}