// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class CollegeProfile
    {
        public CollegeProfile()
        {
            Admission = new HashSet<Admission>();
            CandidateCollegeMapping = new HashSet<CandidateCollegeMapping>();
            CollegeAttachments = new HashSet<CollegeAttachments>();
            CollegeCourseSpecializationMapping = new HashSet<CollegeCourseSpecializationMapping>();
            CollegeStudentMapping = new HashSet<CollegeStudentMapping>();
        }

        [Key]
        public Guid CollegeProfileId { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(450)]
        public string LoginId { get; set; }
        public bool? IsActive { get; set; }
        [Column("College_Contact")]
        public long? CollegeContact { get; set; }
        [Column("College_Email")]
        [StringLength(100)]
        public string CollegeEmail { get; set; }
        [StringLength(500)]
        public string LogoPath { get; set; }
        [StringLength(500)]
        public string AttachementPath { get; set; }
        [StringLength(500)]
        public string Reviews { get; set; }
        public int? Ratings { get; set; }
        [StringLength(450)]
        public string CollegeWebsiteLink { get; set; }
        public string About { get; set; }
        [Column("College_Address")]
        [StringLength(150)]
        public string CollegeAddress { get; set; }
        [StringLength(100)]
        public string CityId { get; set; }
        [StringLength(100)]
        public string DistrictId { get; set; }
        [StringLength(100)]
        public string StateId { get; set; }
        [StringLength(100)]
        public string CountryId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }
        [Column("EnablePPOFlag")]
        public bool? EnablePpoflag { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CollegeProfileCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(LoginId))]
        [InverseProperty(nameof(AspNetUsers.CollegeProfileLogin))]
        public virtual AspNetUsers Login { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.CollegeProfileUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
        [InverseProperty("CollegeProfile")]
        public virtual ICollection<Admission> Admission { get; set; }
        [InverseProperty("CollegeProfile")]
        public virtual ICollection<CandidateCollegeMapping> CandidateCollegeMapping { get; set; }
        [InverseProperty("CollegeProfile")]
        public virtual ICollection<CollegeAttachments> CollegeAttachments { get; set; }
        [InverseProperty("CollegeProfile")]
        public virtual ICollection<CollegeCourseSpecializationMapping> CollegeCourseSpecializationMapping { get; set; }
        [InverseProperty("CollegeProfile")]
        public virtual ICollection<CollegeStudentMapping> CollegeStudentMapping { get; set; }
    }
}