// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class CollegeStudentMapping
    {
        [Key]
        public Guid CollegeStudentMappingId { get; set; }
        public Guid? CollegeProfileId { get; set; }
        [Required]
        [StringLength(450)]
        public string LoginId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(500)]
        public string Feedback { get; set; }
        public int? FeedbackRating { get; set; }
        public Guid? CourseId { get; set; }

        [ForeignKey(nameof(CollegeProfileId))]
        [InverseProperty("CollegeStudentMapping")]
        public virtual CollegeProfile CollegeProfile { get; set; }
        [ForeignKey(nameof(CourseId))]
        [InverseProperty(nameof(CourseMaster.CollegeStudentMapping))]
        public virtual CourseMaster Course { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CollegeStudentMappingCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(LoginId))]
        [InverseProperty(nameof(AspNetUsers.CollegeStudentMappingLogin))]
        public virtual AspNetUsers Login { get; set; }
    }
}