// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class CollegeAttachments
    {
        public Guid? CollegeProfileId { get; set; }
        public string Name { get; set; }
        public string AttachmentPath { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Key]
        public Guid Id { get; set; }

        [ForeignKey(nameof(CollegeProfileId))]
        [InverseProperty("CollegeAttachments")]
        public virtual CollegeProfile CollegeProfile { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CollegeAttachmentsCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.CollegeAttachmentsModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
    }
}