// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class CompanyProfile
    {
        [Key]
        public Guid CompanyProfileId { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(450)]
        public string LoginId { get; set; }
        public bool? IsActive { get; set; }
        [Column("Company_Contact")]
        public long? CompanyContact { get; set; }
        [Column("Company_Email")]
        [StringLength(100)]
        public string CompanyEmail { get; set; }
        [StringLength(500)]
        public string LogoPath { get; set; }
        [StringLength(500)]
        public string AttachementPath { get; set; }
        [StringLength(500)]
        public string Reviews { get; set; }
        public int? Ratings { get; set; }
        [StringLength(450)]
        public string CompanyWebsiteLink { get; set; }
        public string About { get; set; }
        [Column("Company_Address")]
        [StringLength(150)]
        public string CompanyAddress { get; set; }
        [StringLength(100)]
        public string CityId { get; set; }
        [StringLength(100)]
        public string DistrictId { get; set; }
        [StringLength(100)]
        public string StateId { get; set; }
        [StringLength(100)]
        public string CountryId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CompanyProfileCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(LoginId))]
        [InverseProperty(nameof(AspNetUsers.CompanyProfileLogin))]
        public virtual AspNetUsers Login { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.CompanyProfileUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
    }
}