// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class CourseMaster
    {
        public CourseMaster()
        {
            Admission = new HashSet<Admission>();
            CollegeCourseSpecializationMapping = new HashSet<CollegeCourseSpecializationMapping>();
            CollegeStudentMapping = new HashSet<CollegeStudentMapping>();
            CourseSpecializationMapping = new HashSet<CourseSpecializationMapping>();
            Padisclaimer = new HashSet<Padisclaimer>();
            PamonthlyTest = new HashSet<PamonthlyTest>();
            Paquestionnaire = new HashSet<Paquestionnaire>();
            PatestScenario = new HashSet<PatestScenario>();
            PatrainingContentMaster = new HashSet<PatrainingContentMaster>();
        }

        [Key]
        public Guid CourseId { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }
        [StringLength(50)]
        public string Type { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CourseMasterCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.CourseMasterUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Admission> Admission { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<CollegeCourseSpecializationMapping> CollegeCourseSpecializationMapping { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<CollegeStudentMapping> CollegeStudentMapping { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<CourseSpecializationMapping> CourseSpecializationMapping { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Padisclaimer> Padisclaimer { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<PamonthlyTest> PamonthlyTest { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Paquestionnaire> Paquestionnaire { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<PatestScenario> PatestScenario { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<PatrainingContentMaster> PatrainingContentMaster { get; set; }
    }
}