// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class Course
    {
        public Course()
        {
            Disclaimer = new HashSet<Disclaimer>();
            Questionnaire = new HashSet<Questionnaire>();
            TestScenario = new HashSet<TestScenario>();
            TrainingContentsMaster = new HashSet<TrainingContentsMaster>();
            UserCourses = new HashSet<UserCourses>();
        }

        [Key]
        public Guid CourseId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal Fee { get; set; }
        public string Description { get; set; }
        [StringLength(10)]
        public string IsActive { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [Column("TestDuration ")]
        public int? TestDuration { get; set; }
        [StringLength(50)]
        public string Type { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.CourseCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.CourseModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Disclaimer> Disclaimer { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Questionnaire> Questionnaire { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<TestScenario> TestScenario { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<TrainingContentsMaster> TrainingContentsMaster { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<UserCourses> UserCourses { get; set; }
    }
}