// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class DisclaimerAccetped
    {
        [Key]
        [Column("DisclaimerAcceptedID")]
        public Guid DisclaimerAcceptedId { get; set; }
        public Guid? UserProfileId { get; set; }
        public Guid? DisclaimerId { get; set; }
        public bool? IsAccepted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [Column("UserCoursesID")]
        public Guid? UserCoursesId { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.DisclaimerAccetped))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(DisclaimerId))]
        [InverseProperty("DisclaimerAccetped")]
        public virtual Disclaimer Disclaimer { get; set; }
        [ForeignKey(nameof(UserCoursesId))]
        [InverseProperty("DisclaimerAccetped")]
        public virtual UserCourses UserCourses { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("DisclaimerAccetped")]
        public virtual UserProfile UserProfile { get; set; }
    }
}