// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class DistrictMaster
    {
        public DistrictMaster()
        {
            Address = new HashSet<Address>();
            CityMaster = new HashSet<CityMaster>();
            JobMaster = new HashSet<JobMaster>();
        }

        [Key]
        public Guid DistrictId { get; set; }
        [Required]
        public string Name { get; set; }
        public Guid? StateId { get; set; }
        [StringLength(10)]
        public string IsActive { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.DistrictMasterCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.DistrictMasterModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [ForeignKey(nameof(StateId))]
        [InverseProperty(nameof(StateMaster.DistrictMaster))]
        public virtual StateMaster State { get; set; }
        [InverseProperty("District")]
        public virtual ICollection<Address> Address { get; set; }
        [InverseProperty("District")]
        public virtual ICollection<CityMaster> CityMaster { get; set; }
        [InverseProperty("District")]
        public virtual ICollection<JobMaster> JobMaster { get; set; }
    }
}