// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class EducationMaster
    {
        public EducationMaster()
        {
            CollegeCourseSpecializationMapping = new HashSet<CollegeCourseSpecializationMapping>();
            JobQualification = new HashSet<JobQualification>();
            Qualification = new HashSet<Qualification>();
        }

        [Key]
        public Guid EducationId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        public string Description { get; set; }
        [StringLength(10)]
        public string IsActive { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string Type { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.EducationMasterCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.EducationMasterModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [InverseProperty("Education")]
        public virtual ICollection<CollegeCourseSpecializationMapping> CollegeCourseSpecializationMapping { get; set; }
        [InverseProperty("Education")]
        public virtual ICollection<JobQualification> JobQualification { get; set; }
        [InverseProperty("Education")]
        public virtual ICollection<Qualification> Qualification { get; set; }
    }
}