// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class OtpMaster
    {
        [Key]
        public Guid OtpMasterId { get; set; }
        public long Otp { get; set; }
        [StringLength(50)]
        public string EmailId { get; set; }
        public long? MobileNo { get; set; }
        [StringLength(50)]
        public string Username { get; set; }
        [StringLength(10)]
        public string IsVerified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.OtpMaster))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
    }
}