// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    [Table("PACandidateResult")]
    public partial class PacandidateResult
    {
        public PacandidateResult()
        {
            PaquestionnaireResult = new HashSet<PaquestionnaireResult>();
            PatestCaseAttachments = new HashSet<PatestCaseAttachments>();
            PavideoQuestionResult = new HashSet<PavideoQuestionResult>();
        }

        [Key]
        [Column("PACandidateResultId")]
        public Guid PacandidateResultId { get; set; }
        [Column("UserProfileID")]
        public Guid? UserProfileId { get; set; }
        public int? TestDuration { get; set; }
        public bool? IsCompleted { get; set; }
        public bool? IsCleared { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TestStarted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RemainingTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TestEnd { get; set; }
        [Column("MonthlyTestID")]
        public Guid? MonthlyTestId { get; set; }
        public int? TestAttempt { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Score { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.PacandidateResult))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(MonthlyTestId))]
        [InverseProperty(nameof(PamonthlyTest.PacandidateResult))]
        public virtual PamonthlyTest MonthlyTest { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("PacandidateResult")]
        public virtual UserProfile UserProfile { get; set; }
        [InverseProperty("CandidateResult")]
        public virtual ICollection<PaquestionnaireResult> PaquestionnaireResult { get; set; }
        [InverseProperty("PaCandidateResult")]
        public virtual ICollection<PatestCaseAttachments> PatestCaseAttachments { get; set; }
        [InverseProperty("CandidateResult")]
        public virtual ICollection<PavideoQuestionResult> PavideoQuestionResult { get; set; }
    }
}