// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    [Table("PAMonthlyTest")]
    public partial class PamonthlyTest
    {
        public PamonthlyTest()
        {
            PacandidateResult = new HashSet<PacandidateResult>();
            PadisclaimerAccetped = new HashSet<PadisclaimerAccetped>();
        }

        [Key]
        public Guid MonthlyTestId { get; set; }
        public Guid CourseId { get; set; }
        [Column("Month ")]
        public int? Month { get; set; }
        public int? Year { get; set; }
        [Column("TestType ")]
        [StringLength(50)]
        public string TestType { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty(nameof(CourseMaster.PamonthlyTest))]
        public virtual CourseMaster Course { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.PamonthlyTestCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.PamonthlyTestUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
        [InverseProperty("MonthlyTest")]
        public virtual ICollection<PacandidateResult> PacandidateResult { get; set; }
        [InverseProperty("MonthlyTest")]
        public virtual ICollection<PadisclaimerAccetped> PadisclaimerAccetped { get; set; }
    }
}