// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    [Table("PAQuestionnaireResult")]
    public partial class PaquestionnaireResult
    {
        [Key]
        [Column("PAQuestionnaireResultId")]
        public Guid PaquestionnaireResultId { get; set; }
        public Guid? CandidateResultId { get; set; }
        [Column("PAQuestionnaireId")]
        public Guid? PaquestionnaireId { get; set; }
        public bool? AnswerProvided { get; set; }
        public bool? IsCorrectAnswer { get; set; }
        public int? QuestionOrder { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        public int? OptionSelected { get; set; }
        public Guid? TrainingContentId { get; set; }

        [ForeignKey(nameof(CandidateResultId))]
        [InverseProperty(nameof(PacandidateResult.PaquestionnaireResult))]
        public virtual PacandidateResult CandidateResult { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.PaquestionnaireResultCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.PaquestionnaireResultModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [ForeignKey(nameof(PaquestionnaireId))]
        [InverseProperty("PaquestionnaireResult")]
        public virtual Paquestionnaire Paquestionnaire { get; set; }
    }
}