// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    [Table("PATestScenario")]
    public partial class PatestScenario
    {
        [Key]
        [Column("PATestScenarioId")]
        public Guid PatestScenarioId { get; set; }
        public Guid? CourseId { get; set; }
        public Guid? TrainingContentsId { get; set; }
        public bool? IsActive { get; set; }
        public int? NoOfQuestions { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty(nameof(CourseMaster.PatestScenario))]
        public virtual CourseMaster Course { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.PatestScenarioCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(TrainingContentsId))]
        [InverseProperty(nameof(PatrainingContentMaster.PatestScenario))]
        public virtual PatrainingContentMaster TrainingContents { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.PatestScenarioUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
    }
}