// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    [Table("PATrainingContentMaster")]
    public partial class PatrainingContentMaster
    {
        public PatrainingContentMaster()
        {
            Paquestionnaire = new HashSet<Paquestionnaire>();
            PatestScenario = new HashSet<PatestScenario>();
        }

        [Key]
        public Guid TrainingContentId { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(500)]
        public string Path { get; set; }
        [StringLength(20)]
        public string ContentType { get; set; }
        public Guid? CourseId { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty(nameof(CourseMaster.PatrainingContentMaster))]
        public virtual CourseMaster Course { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.PatrainingContentMasterCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.PatrainingContentMasterModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [InverseProperty("PatrainingContent")]
        public virtual ICollection<Paquestionnaire> Paquestionnaire { get; set; }
        [InverseProperty("TrainingContents")]
        public virtual ICollection<PatestScenario> PatestScenario { get; set; }
    }
}