// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    [Table("PAVideoQuestionResult")]
    public partial class PavideoQuestionResult
    {
        [Key]
        public Guid VideoQuestionResultId { get; set; }
        [Column("UserProfileID")]
        public Guid? UserProfileId { get; set; }
        public Guid? CandidateResultId { get; set; }
        [StringLength(300)]
        public string VideoAbsolutePath { get; set; }
        [StringLength(300)]
        public string VideoName { get; set; }
        [Column("PAQuestionnaireId")]
        public Guid? PaquestionnaireId { get; set; }
        public int? QuestionOrder { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        public string Feedback { get; set; }
        public int? Score { get; set; }

        [ForeignKey(nameof(CandidateResultId))]
        [InverseProperty(nameof(PacandidateResult.PavideoQuestionResult))]
        public virtual PacandidateResult CandidateResult { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.PavideoQuestionResultCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.PavideoQuestionResultModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [ForeignKey(nameof(PaquestionnaireId))]
        [InverseProperty("PavideoQuestionResult")]
        public virtual Paquestionnaire Paquestionnaire { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("PavideoQuestionResult")]
        public virtual UserProfile UserProfile { get; set; }
    }
}