// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class PpoInfo
    {
        [Key]
        public Guid Id { get; set; }
        public Guid UserProfileId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Score { get; set; }
        [StringLength(50)]
        public string Position { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Salary { get; set; }
        public bool? IsDownloded { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [Column("PpoLogicID")]
        public Guid? PpoLogicId { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.PpoInfoCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.PpoInfoUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("PpoInfo")]
        public virtual UserProfile UserProfile { get; set; }
    }
}