// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class PpoLogic
    {
        [Key]
        [Column("PpoLogicID")]
        public Guid PpoLogicId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? StartScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? EndScore { get; set; }
        [StringLength(50)]
        public string Position { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Salary { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.PpoLogic))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
    }
}