// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class Qualification
    {
        [Key]
        public Guid QualificaitonId { get; set; }
        public Guid UserProfileId { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [Required]
        [StringLength(200)]
        public string UniversityName { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal TotalMarks { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal MarksObtained { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Percentage { get; set; }
        [Column(TypeName = "date")]
        public DateTime CompletionYear { get; set; }
        public long ChronologicalOrder { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        public Guid? EducationId { get; set; }
        public bool? IsHighestQualification { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.QualificationCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(EducationId))]
        [InverseProperty(nameof(EducationMaster.Qualification))]
        public virtual EducationMaster Education { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.QualificationModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("Qualification")]
        public virtual UserProfile UserProfile { get; set; }
    }
}