// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class SentNotifications
    {
        [Key]
        [Column("SentNotificationsID")]
        public Guid SentNotificationsId { get; set; }
        [Column("EmployerID")]
        public Guid? EmployerId { get; set; }
        [Column("CandidateID")]
        public Guid? CandidateId { get; set; }
        public bool? IsNotificationSent { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CandidateId))]
        [InverseProperty(nameof(UserProfile.SentNotificationsCandidate))]
        public virtual UserProfile Candidate { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.SentNotificationsCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(EmployerId))]
        [InverseProperty(nameof(UserProfile.SentNotificationsEmployer))]
        public virtual UserProfile Employer { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.SentNotificationsModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
    }
}