// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class ShortlistedCandidates
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? AppliedJobId { get; set; }
        [Column("CandidateID")]
        public Guid? CandidateId { get; set; }
        [Column("EmployerID")]
        public Guid? EmployerId { get; set; }
        public Guid? JobId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NotificationDate { get; set; }
        [StringLength(100)]
        public string Status { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        public bool? IsNotificationSent { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(AppliedJobId))]
        [InverseProperty(nameof(AppliedJobs.ShortlistedCandidates))]
        public virtual AppliedJobs AppliedJob { get; set; }
        [ForeignKey(nameof(CandidateId))]
        [InverseProperty(nameof(UserProfile.ShortlistedCandidatesCandidate))]
        public virtual UserProfile Candidate { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.ShortlistedCandidatesCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(EmployerId))]
        [InverseProperty(nameof(UserProfile.ShortlistedCandidatesEmployer))]
        public virtual UserProfile Employer { get; set; }
        [ForeignKey(nameof(JobId))]
        [InverseProperty(nameof(JobMaster.ShortlistedCandidates))]
        public virtual JobMaster Job { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.ShortlistedCandidatesModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
    }
}