// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class SpecializationMaster
    {
        public SpecializationMaster()
        {
            CollegeCourseSpecializationMapping = new HashSet<CollegeCourseSpecializationMapping>();
            CourseSpecializationMapping = new HashSet<CourseSpecializationMapping>();
        }

        [Key]
        public Guid SpecializationId { get; set; }
        [StringLength(100)]
        public string SpecializationName { get; set; }
        public string Description { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.SpecializationMasterCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.SpecializationMasterUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
        [InverseProperty("Specialzation")]
        public virtual ICollection<CollegeCourseSpecializationMapping> CollegeCourseSpecializationMapping { get; set; }
        [InverseProperty("Specialization")]
        public virtual ICollection<CourseSpecializationMapping> CourseSpecializationMapping { get; set; }
    }
}