// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class StateMaster
    {
        public StateMaster()
        {
            Address = new HashSet<Address>();
            DistrictMaster = new HashSet<DistrictMaster>();
            JobMaster = new HashSet<JobMaster>();
        }

        [Key]
        public Guid StateId { get; set; }
        [Required]
        public string Name { get; set; }
        public Guid? CountryId { get; set; }
        [StringLength(10)]
        public string IsActive { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CountryId))]
        [InverseProperty(nameof(CountryMaster.StateMaster))]
        public virtual CountryMaster Country { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.StateMasterCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(ModifiedBy))]
        [InverseProperty(nameof(AspNetUsers.StateMasterModifiedByNavigation))]
        public virtual AspNetUsers ModifiedByNavigation { get; set; }
        [InverseProperty("State")]
        public virtual ICollection<Address> Address { get; set; }
        [InverseProperty("State")]
        public virtual ICollection<DistrictMaster> DistrictMaster { get; set; }
        [InverseProperty("State")]
        public virtual ICollection<JobMaster> JobMaster { get; set; }
    }
}