// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class TestScenario
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? CourseId { get; set; }
        public Guid? TrainingContentsId { get; set; }
        public bool? IsActive { get; set; }
        public int? NoOfQuestions { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [StringLength(450)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("TestScenario")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.TestScenarioCreatedByNavigation))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(TrainingContentsId))]
        [InverseProperty(nameof(TrainingContentsMaster.TestScenario))]
        public virtual TrainingContentsMaster TrainingContents { get; set; }
        [ForeignKey(nameof(UpdatedBy))]
        [InverseProperty(nameof(AspNetUsers.TestScenarioUpdatedByNavigation))]
        public virtual AspNetUsers UpdatedByNavigation { get; set; }
    }
}