// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace XpertAditusUI.Models
{
    public partial class UserCourses
    {
        public UserCourses()
        {
            CandidateResult = new HashSet<CandidateResult>();
            CandidateTrainingStatus = new HashSet<CandidateTrainingStatus>();
            DisclaimerAccetped = new HashSet<DisclaimerAccetped>();
            PaymentHistory = new HashSet<PaymentHistory>();
        }

        [Key]
        [Column("UserCoursesID")]
        public Guid UserCoursesId { get; set; }
        [Column("CourseID")]
        public Guid? CourseId { get; set; }
        [Column("UserProfileID")]
        public Guid? UserProfileId { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("UserCourses")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(AspNetUsers.UserCourses))]
        public virtual AspNetUsers CreatedByNavigation { get; set; }
        [ForeignKey(nameof(UserProfileId))]
        [InverseProperty("UserCourses")]
        public virtual UserProfile UserProfile { get; set; }
        [InverseProperty("UserCourses")]
        public virtual ICollection<CandidateResult> CandidateResult { get; set; }
        [InverseProperty("UserCourses")]
        public virtual ICollection<CandidateTrainingStatus> CandidateTrainingStatus { get; set; }
        [InverseProperty("UserCourses")]
        public virtual ICollection<DisclaimerAccetped> DisclaimerAccetped { get; set; }
        [InverseProperty("UserCourses")]
        public virtual ICollection<PaymentHistory> PaymentHistory { get; set; }
    }
}